git:
  depth: 1

addons:
  homebrew:
    brewfile: true
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/nasm'
    packages:
      - autoconf
      - automake
      - build-essential
      - cmake
      - git
      - libass-dev
      - libbz2-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libharfbuzz-dev
      - libjansson-dev
      - liblzma-dev
      - libmp3lame-dev
      - libogg-dev
      - libopus-dev
      - libsamplerate-dev
      - libspeex-dev
      - libtheora-dev
      - libtool
      - libtool-bin
      - libvorbis-dev
      - libx264-dev
      - libxml2-dev
      - m4
      - make
      - patch
      - pkg-config
      - python
      - tar
      - yasm
      - zlib1g-dev
      - intltool
      - libappindicator-dev
      - libdbus-glib-1-dev
      - libglib2.0-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgtk-3-dev
      - libgudev-1.0-dev
      - libnotify-dev
      - libwebkitgtk-3.0-dev
      - nasm
      - pax
      - mingw-w64

matrix:
  include:
    - os: linux
      dist: xenial
      env: BUILD_MINGW=false
    - os: linux
      dist: xenial
      env: BUILD_MINGW=true
    - os: osx
      osx_image: xcode10.1
      nv: BUILD_MINGW=false

language: c

script:

# Linux Build Support
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_MINGW" == false  ]]; then ./configure --disable-gst --launch --launch-jobs=0 ; fi

# MinGW Build Support
- if [[ "$BUILD_MINGW" == true ]]; then ./configure --cross=x86_64-w64-mingw32 --enable-nvenc --enable-qsv --enable-vce  && cd build && make -j 2 ; fi

# Macos Build Support
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure && cd build && make -j 2 ; fi


cache:
  directories:
  - $HOME/toolchains
