git:
  depth: 1

addons:
  homebrew:
    brewfile: true
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/nasm'
      - sourceline: 'ppa:jonathonf/gtk3.22'
    packages:
      - autoconf
      - automake
      - build-essential
      - cmake
      - git
      - libass-dev
      - libbz2-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libharfbuzz-dev
      - libjansson-dev
      - liblzma-dev
      - libmp3lame-dev
      - libogg-dev
      - libopus-dev
      - libsamplerate-dev
      - libspeex-dev
      - libtheora-dev
      - libtool
      - libtool-bin
      - libvorbis-dev
      - libx264-dev
      - libxml2-dev
      - m4
      - make
      - patch
      - pkg-config
      - python
      - tar
      - yasm
      - zlib1g-dev
      - intltool
      - libappindicator-dev
      - libdbus-glib-1-dev
      - libglib2.0-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgtk-3-dev
      - libgudev-1.0-dev
      - libnotify-dev
      - libwebkitgtk-3.0-dev
      - nasm
      - pax
      - mingw-w64

matrix:
  include:
    - os: linux
      dist: xenial
      env: ARGS="--disable-gst --launch --launch-jobs=0"
    - os: linux
      dist: xenial
      env: ARGS="--cross=x86_64-w64-mingw32 --enable-nvenc --enable-qsv --enable-vce"
    - os: osx

language: c

script: travis_wait 50 ./configure $ARGS && cd build && travis_wait 50 make V=0 -j 2


cache:
  directories:
  - $HOME/toolchains
